dist: trusty

sudo: false

language: php

php:
  - 7.1

install:
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - php wp-cli.phar --info

script:
  php test.php
