dist: trusty

sudo: false

language: php

php:
  - 7.1

install:
  # Install WP CLI
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - php wp-cli.phar --info
  # Install WordPress
  - mkdir wordpress
  - php wp-cli.phar core download
  - php wp-cli.phar config create
  - php wp-cli.phar db create
  - php wp-cli.phar core install --title=Test --admin_user=test --admin_email=test@example.com --skip-email
  # Install Composer
  - composer install

script:
  php test.php
