dist: trusty

sudo: false

language: php

php:
  - 7.1

install:
  # Install WP CLI
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - php wp-cli.phar --info
  # Install WordPress
  - mkdir wordpress
  - php wp-cli.phar core download --path=wordpress
  - php wp-cli.phar config --dbname=wordpress_test --dbuser=root --dbpass=
  - php wp-cli.phar db create
  - php wp-cli.phar core install --url=http://wordpress.test/ --title=Test --admin_user=test --admin_email=test@example.com --skip-email

script:
  php test.php
